---
title: "README"
format: html
editor: visual
---

# A dynamic foraging habitat distribution estimate for green turtles in the Great Barrier Reef

## Usage Instructions

The R scripts should be run in this order:

1.  **prep&presences.Rmd** data filtering and state-space modelling. Calls **LoadPackages_PA.R** (adapted from Hazen et al. 2021) & raw data (available upon reasonable request from Queensland Department of Environment, Science and Innovation's Threatened Species Unit).
2.  **Pseudoabsences.R** generate pseudo-absences (background and correlated random walk). Calls **PseudoFunctions.R** (adapted from Hazen et al. 2021). Run on a containerised environment on the JCU HPC.
3.  **AppendtoEnviroData.Rmd** workflow for appending environmental covariates to presences and pseudo-absences (see Table 1 in manuscript). Calls the following R scripts:
    a)  **ExtractEReefs.R, ExtractEReefsCRW.R** & **ExtractEReefsbackground.R** append daily eReefs variables to presences/pseudo-absences. Run on a containerised environment on the JCU HPC.
4.  **habitatmodel.Rmd** create BRT models, quantify relative importance of environmental covariates, generate partial plots and predict to GBR grid at 2 time points.

## R software information

> sessionInfo() R version 4.3.1 (2023-06-16 ucrt) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 11 x64 (build 22621)

Matrix products: default

locale: \[1\] LC_COLLATE=English_Australia.utf8 LC_CTYPE=English_Australia.utf8 LC_MONETARY=English_Australia.utf8 LC_NUMERIC=C\
\[5\] LC_TIME=English_Australia.utf8

time zone: Australia/Brisbane tzcode source: internal

attached base packages: \[1\] stats graphics grDevices utils datasets methods base

loaded via a namespace (and not attached): \[1\] gtable_0.3.4 dplyr_1.1.2 compiler_4.3.1 visdat_0.6.0 tidyselect_1.2.0 Rcpp_1.0.11 spatialEco_2.0-2 scales_1.2.1\
\[9\] yaml_2.3.7 fastmap_1.1.1 lattice_0.21-8 ggplot2_3.4.3 R6_2.5.1 generics_0.1.3 pdp_0.8.1 knitr_1.43\
\[17\] iterators_1.0.14 tibble_3.2.1 munsell_0.5.0 pillar_1.9.0 rlang_1.1.1 utf8_1.2.3 sp_2.0-0 terra_1.7-39\
\[25\] xfun_0.40 cli_3.6.1 magrittr_2.0.3 digest_0.6.33 foreach_1.5.2 grid_4.3.1 rstudioapi_0.15.0 lifecycle_1.0.4\
\[33\] vctrs_0.6.3 evaluate_0.23 glue_1.6.2 raster_3.6-23 codetools_0.2-19 fansi_1.0.4 colorspace_2.1-0 rmarkdown_2.24\
\[41\] tools_4.3.1 pkgconfig_2.0.3 htmltools_0.5.6

### JCU HPC information

R v4.1.2u2 software is available in a singularity container.

Platform: x86_64-pc-linux-gnu (64-bit)

\> sessionInfo()

R version 4.1.2 (2021-11-01)

Platform: x86_64-pc-linux-gnu (64-bit)

Running under: Ubuntu 22.04.2 LTS

Matrix products: default

BLAS: /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3

LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so

locale:

\[1\] C

attached base packages:

\[1\] stats graphics grDevices utils datasets methods base

loaded via a namespace (and not attached):

\[1\] compiler_4.1.2

## Data Description

### Primary data

Input for habitat model runs. Contains turtle presences (from state-space modelling) and pseudoabsences (background and correlated random walk).

"20240704ssm.Rds" = Presences, i.e., output from prep&presences.Rmd, estimated locations of turtles at 12 hour intervals using movement persistence models in aniMotum.

Outputs from Pseudoabsences.R & AppendtoEnviroData.Rmd=

1.  "track.csv" = presences
2.  "background.csv" = background pseudo-absences
3.  "crw.csv" = correlated random walk pseudo-absences

#### Variable descriptions

-   id: Unique identifier for turtle tracks. Tracks with gaps of \>48 hours were considered independent. Independent tracks from a single turtle are numbered "\_0", "\_1" etc.
-   converged: Whether ssm model converged
-   pdHess: Whether the Hessian matrix was positive-definite and could be solved to obtain parameter standard errors
-   pmodel: SSM model type; "mp" is movement persistence
-   id1: A combination of the tracker number and the turtle's Primary flipper tag number
-   lat: Latitude
-   lon: Longitude
-   data_type: 'track' = presence; 'background' or 'crw' = pseudo-absences
-   date: Calendar date GMT
-   aus.date: Calendar date AEST
-   iteration: for pseudo-absences,
-   COMMUNITY: Seagrass community type
-   builtfeature: Within spatial buffer of 0.0014 decimal degrees of built feature
-   geohab: Geomorphic habitats of Australia
-   dist2recboatfeat: Distance to boat ramps
-   Dist2Rivers1: Distance to rivers
-   dist2reefs1: Distance to reefs
-   bathy1: Bathymetry
-   dist2coast1_2: Distance to coast
-   seagrassP1: Seagrass probability
-   tidalexposure1: Tidal exposure
-   mmpexposure1: Longterm exposure to above guideline value concentrations of land-sourced pollutants: "Chronic floodwater exposure"
-   mmpfrequency1: Longterm frequency of water types 1&2: "Acute flood frequency"
-   salt: Salinity
-   temp: Temperature
-   mean_cur: Mean seawater velocity
-   mean_wspeed: Mean wind speed
-   ZooL_N: Large zooplankton nitrogen
-   EFI: Ecology fine inorganics (i.e., sum of fine sediment and mud concentrations, derived as total suspended solids/1000)
-   Secchi: Secchi depth
-   geomorph: Geomorphology
-   deamangrove: Distance to mangroves
-   slope1: Slope
-   ruggedness1: Ruggedness

### Secondary data

Input rasters for grid predictions as .tif files, excludes MMP grids (exposure and frequency, which are available upon reasonable request from JCU TropWATER).

-   class : RasterLayer

-   dimensions : 23531, 21698, 510575638 (nrow, ncol, ncell)

-   resolution : 100, 100 (x, y)

-   extent : 961853.5, 3131654, -3445441, -1092341 (xmin, xmax, ymin, ymax)

-   crs : +proj=aea +lat_0=0 +lon_0=132 +lat_1=-18 +lat_2=-36 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs

    -   bathy.tif - Bathymetry
    -   builtfeat500.tif - Built features, resampled to 500m pixels
    -   COMMUNITY500.tif - Seagrass community type, resampled to 500m pixels
    -   dist2coast.tif - Distance to coast
    -   dist2recboats.tif - Distance to boat ramps
    -   dist2reefs.tif - Distance to reefs
    -   dist2rivers.tif - Distance to rivers
    -   EFI2010.tif - Ecology fine inorganics December 2010
    -   EFI2022.tif - Ecology fine inorganics December 2022
    -   geohab500.tif - Geomorphic habitats resampled to 500m pixels
    -   geomorph500.tif - Geomorphology resampled to 500m pixels
    -   mangroves2010.tif - Distance to mangroves 2010
    -   mangroves2022.tif - Distance to mangroves 2022
    -   mask.tif - Modelled extent
    -   mean_cur2010.tif - Mean surface velocity December 2010
    -   mean_cur2022.tif - Mean surface velocity December 2022
    -   mean_wspeed2010.tif - Mean wind speed December 2010
    -   mean_wspeed2022.tif  - Mean wind speed December 2022
    -   mmpexposure.tif - Longterm exposure to above guideline value concentrations of land-sourced pollutants: "Chronic floodwater exposure" (data available upon reasonable request from JCU TropWATER)
    -   mmpfrequency.tif - Longterm frequency of water types 1&2: "Acute flood frequency" (data available upon reasonable request from JCU TropWATER)
    -   ruggedness.tif - Ruggedness
    -   salt2010.tif - Salinity December 2010
    -   salt2022.tif - Salinity December 2022
    -   seagrassp.tif - Seagrass probability
    -   Secchi2010.tif - Secchi depth December 2010
    -   Secchi2022.tif - Secchi depth December 2022
    -   slope.tif - Slope
    -   temp2010.tif - Temperature December 2010
    -   temp2022.tif - Temperature December 2022
    -   tidalexposure.tif - Tidal Exposure
    -   ZooL_N2010.tif - Large zooplankton Nitorogen December 2010
    -   ZooL_N2022.tif - Large zooplankton Nitrogen December 2022

## Final model outputs

Ascii grids named as:

GL or unmod, indicating whether Port Curtis (GL) or Shoalwater Bay and Raine Island (unmod) data were used.

If 2022 is specified, model prediction is based on environmental predictor data from December 2022, otherwise environmental predictor data are from December 2010.

-   backgroundGL_preds.asc

-   backgroundGL_preds2022.asc

-   backgroundunmod_preds.asc

-   backgroundunmod_preds2022.asc

-   crwGL_preds.asc

-   crwCL_preds2022.asc

-   crwunmod_preds.asc

-   crwunmod_preds2022.asc
